### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by LemmaEOF** [Earthcomputer/MinecraftDev#12] opened 2020-06-03 07:19 UTC
IDEA Ultimate 2019.3.3
MacOS 10.15.5 beta 19F83c
MCDev 2019.3-1.3.2-earth.23

There are a few non-critical problems I've noticed with the current Fabric project creation workflow:
- Creating a new Fabric project makes .ipr, .iws, and .imp files, while newer versions of Idea only create .idea/ folders when importing a project
- Creating a new Fabric project does not create it with the necessary Minecraft Client and Minecraft Server run configurations, and they cannot be found in the `Edit Configurations...` menu
- The default Loom version is 0.2.6-SNAPSHOT, even though 0.2.7-SNAPSHOT should be used instead
- Defining a client mod initializer class to go at `net.fabricmc.examplemod.ClientEample` will create a class at the right location but with `package net.fabricmc.examplemod.client;` in the Java file

**Comment by ghost** [comment] 2020-06-19 20:10
Just as an addendum for future references to this issue, the default should be 0.4-SNAPSHOT now :)

**Comment by Earthcomputer** [comment] 2020-07-03 10:15
Thanks for your report! These issues will be addressed in the upstream version: https://github.com/minecraft-dev/MinecraftDev/pull/733.
- [ ] Creating a new Fabric project makes .ipr, .iws, and .imp files, while newer versions of Idea only create .idea/ folders when importing a project (https://github.com/minecraft-dev/MinecraftDev/issues/735)
- [ ] Creating a new Fabric project does not create it with the necessary Minecraft Client and Minecraft Server run configurations, and they cannot be found in the `Edit Configurations...` menu (cannot reproduce)
- [x] The default Loom version is 0.2.6-SNAPSHOT, even though 0.2.7-SNAPSHOT should be used instead
- [x] Defining a client mod initializer class to go at `net.fabricmc.examplemod.ClientEample` will create a class at the right location but with package `net.fabricmc.examplemod.client;` in the Java file

**Closed as completed** 2020-07-03 10:43 UTC
