### ISSUE TITLE
Environment check does not do flow analysis

### ISSUE THREAD

**Issue by LoganDark** [Earthcomputer/MinecraftDev#10] opened 2020-04-27 10:41 UTC
* Plugin version: 2019.2-1.3.2-earth.23
* IntelliJ version: IDEA 2019.2.3 Ultimate
* Operating System: macOS 10.14.6
* Target platforms: Fabric Loader

Basically this:

![image](https://user-images.githubusercontent.com/4723091/80363064-850d2a00-8838-11ea-8fca-29f247f6ef1d.png)

There is quite obviously an `if` check that makes sure this is only called in a CLIENT environment, yet MinecraftDev still marks it as an error.

(or more accurately, it triggers the inspection, which IDEA then marks as an error)

**Comment by Earthcomputer** [comment] 2020-04-27 11:47
The issue is, the plugin would need to know all the different checks which prove that you're running on the client. Those checks are modding-platform-dependent, while the sided analysis is not. Before this, I'd like to add intermediary mapping support so that I can check `world.isClient` too, while being safe against yarn renaming this method. Overall, we're not there yet. In the mean-time, you can use a `//noinspection` suppression for cases like these.

Also, you are using the internal `FabricLoader` class there, you want the other one.

**Comment by LoganDark** [comment] 2020-04-27 11:48
> Also, you are using the internal FabricLoader class there, you want the other one.

I am not. The mod I am contributing to is. Here is the code I use:

![image](https://user-images.githubusercontent.com/4723091/80368943-56944c80-8842-11ea-9da7-b75ae2973792.png)

**Comment by Earthcomputer** [comment] 2020-04-27 11:49
Ok well that's irrelevant.

**Comment by Earthcomputer** [comment] 2020-07-03 10:48
I'm going to close this as invalid, as in many cases a `NoClassDefFoundError` can be thrown by the class verifier even if the code can never be run on the server.

**Closed as completed by Earthcomputer** 2020-07-03 10:48 UTC
